import express from "express";
import path from "path";
import dotenv from "dotenv";
import { createServer as createViteServer } from "vite";
import { jsonrepair } from "jsonrepair";
import multer from "multer";

type JointState = {
  base: number;
  shoulder: number;
  elbow: number;
  wristPitch: number;
  wristRoll: number;
  gripper: number;
};

type GeneratedKeyframe = {
  name: string;
  durationMs: number;
  delayAfterMs: number;
  joints: JointState;
  comment: string | null;
};

const jointLimits: Record<keyof JointState, readonly [number, number]> = {
  base: [-180, 180],
  shoulder: [-90, 90],
  elbow: [-120, 120],
  wristPitch: [-90, 90],
  wristRoll: [-180, 180],
  gripper: [0, 100]
};

const clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(max, value));
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null;

// Episode video uploads are buffered in memory, then written to disk in the
// /api/episodes handler once the request is fully parsed — this sidesteps
// multer's field-ordering requirement for disk-storage destination callbacks.
const episodeUpload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 512 * 1024 * 1024 } // 512MB/file cap — generous safety net for short local clips
});

function normalizeSequenceShape(value: unknown): unknown {
  if (Array.isArray(value)) {
    return { keyframes: value };
  }
  if (!isRecord(value) || Array.isArray(value.keyframes)) {
    return value;
  }

  for (const key of ["sequence", "steps", "trajectory", "poses"]) {
    if (Array.isArray(value[key])) {
      return { ...value, keyframes: value[key] };
    }
  }

  return value;
}

function sanitizeSequenceData(value: unknown) {
  value = normalizeSequenceShape(value);
  if (!isRecord(value) || !Array.isArray(value.keyframes)) {
    throw new Error("Ollama response does not contain a sequence of keyframes.");
  }

  const keyframes = value.keyframes.slice(0, 5).flatMap((keyframe, index): GeneratedKeyframe[] => {
    if (!isRecord(keyframe) || !isRecord(keyframe.joints)) {
      return [];
    }

    const jointEntries = Object.entries(jointLimits).map(([joint, [min, max]]) => {
        const rawValue = keyframe.joints[joint];
        if (typeof rawValue !== "number" || !Number.isFinite(rawValue)) {
          return null;
        }
        return [joint, Math.round(clamp(rawValue, min, max) * 10) / 10] as const;
      });

    if (jointEntries.some(entry => entry === null)) {
      return [];
    }
    const joints = Object.fromEntries(jointEntries) as JointState;

    return [{
      name: typeof keyframe.name === "string" && keyframe.name.trim() ? keyframe.name.trim() : `Pose ${index + 1}`,
      durationMs: Math.round(clamp(typeof keyframe.durationMs === "number" ? keyframe.durationMs : 1000, 600, 2000)),
      delayAfterMs: Math.round(clamp(typeof keyframe.delayAfterMs === "number" ? keyframe.delayAfterMs : 0, 0, 5000)),
      joints,
      comment: typeof keyframe.comment === "string" ? keyframe.comment : null
    }];
  });

  if (keyframes.length < 3) {
    throw new Error("Ollama returned fewer than three keyframes.");
  }

  return {
    title: typeof value.title === "string" && value.title.trim() ? value.title.trim() : "AI Generated Routine",
    description: typeof value.description === "string" ? value.description.trim() : "Generated by local Ollama.",
    keyframes
  };
}

// Load local secrets for development before the server reads process.env.
dotenv.config({ path: ".env.local" });
dotenv.config();

async function startServer() {
  const app = express();
  app.use(express.json());
  const PORT = Number(process.env.PORT || 3000);

  const ollamaBaseUrl = (process.env.OLLAMA_BASE_URL || "http://127.0.0.1:11434").replace(/\/$/, "");
  const model = process.env.OLLAMA_MODEL || "ornith:9b";
  const datasetRoot = path.join(process.cwd(), "data", "external", "svla_so100_pickplace");

  // Health check endpoint
  app.get("/api/health", (req, res) => {
    res.json({
      status: "ok",
      robotModel: "SO-ARM100 (6-DOF)",
      ollamaUrl: ollamaBaseUrl,
      model
    });
  });

  // Local, read-only LeRobot dataset inspection. Dataset playback never enters
  // the hardware command path; it is only exposed for synchronized visual review.
  app.get("/api/dataset/svla-so100", async (req, res) => {
    try {
      const infoPath = path.join(datasetRoot, "meta", "info.json");
      const info = JSON.parse(await (await import("node:fs/promises")).readFile(infoPath, "utf8"));
      res.json({
        id: "lerobot/svla_so100_pickplace",
        robotType: info.robot_type,
        episodes: info.total_episodes,
        frames: info.total_frames,
        fps: info.fps,
        cameras: ["top", "wrist"],
        actionJoints: info.features?.action?.names ?? [],
        stateJoints: info.features?.["observation.state"]?.names ?? [],
        videos: {
          top: "/api/dataset/svla-so100/video/top",
          wrist: "/api/dataset/svla-so100/video/wrist"
        }
      });
    } catch {
      res.status(404).json({ error: "The local svla_so100_pickplace dataset is not installed." });
    }
  });

  app.get("/api/dataset/svla-so100/video/:camera", (req, res) => {
    const camera = req.params.camera;
    if (camera !== "top" && camera !== "wrist") {
      return res.status(400).json({ error: "Camera must be top or wrist." });
    }
    const videoPath = path.join(
      datasetRoot,
      "videos",
      `observation.images.${camera}`,
      "chunk-000",
      "file-000.mp4"
    );
    return res.sendFile(videoPath, (error) => {
      const statusCode = (error as (Error & { statusCode?: number }) | null)?.statusCode || 404;
      if (error && !res.headersSent) res.status(statusCode).json({ error: "Dataset video not found." });
    });
  });

  app.get("/api/policy/preview", async (req, res) => {
    try {
      const previewPath = path.join(process.cwd(), "outputs", "policy-preview.json");
      const preview = JSON.parse(await (await import("node:fs/promises")).readFile(previewPath, "utf8"));
      res.json(preview);
    } catch {
      res.status(404).json({ error: "Generate the offline policy preview first." });
    }
  });

  // Save a locally recorded teleoperation episode (two camera videos + a
  // commanded-joint-samples metadata.json) to disk. The client falls back to
  // browser downloads if this fails, so this stays simple: no transactional
  // rollback on a partial write failure.
  app.post(
    "/api/episodes",
    episodeUpload.fields([
      { name: "overview", maxCount: 1 },
      { name: "wrist", maxCount: 1 }
    ]),
    async (req, res) => {
      try {
        const files = req.files as Record<string, Express.Multer.File[]> | undefined;
        const overviewFile = files?.overview?.[0];
        const wristFile = files?.wrist?.[0];
        if (!overviewFile || !wristFile) {
          return res.status(400).json({ error: "Both overview and wrist video files are required." });
        }

        let metadata: Record<string, unknown>;
        try {
          metadata = JSON.parse(String(req.body.metadata));
        } catch {
          return res.status(400).json({ error: "metadata field must be valid JSON." });
        }
        if (
          typeof metadata.startedAt !== "string"
          || typeof metadata.schemaVersion !== "number"
          || !metadata.observations
          || !metadata.actions
        ) {
          return res.status(400).json({ error: "metadata is missing required fields (startedAt, schemaVersion, observations, actions)." });
        }

        const sanitized = (metadata.startedAt as string).replace(/[^a-zA-Z0-9-]/g, "-");
        const episodeName = sanitized.length > 0 ? sanitized : `episode-${Date.now()}`;
        const episodeDirRelative = path.join("data", "local", "episodes", episodeName);
        const episodeDirAbsolute = path.join(process.cwd(), episodeDirRelative);

        const fs = await import("node:fs/promises");
        await fs.mkdir(episodeDirAbsolute, { recursive: true });

        const writeEpisodeFile = async (label: string, filename: string, data: Buffer | string) => {
          try {
            await fs.writeFile(path.join(episodeDirAbsolute, filename), data);
          } catch (writeError) {
            throw new Error(`Failed to write ${label}: ${(writeError as Error).message}`);
          }
        };

        const extensionFor = (mimetype: string) => (mimetype.includes("mp4") ? "mp4" : "webm");
        await writeEpisodeFile("overview video", `overview.${extensionFor(overviewFile.mimetype)}`, overviewFile.buffer);
        await writeEpisodeFile("wrist video", `wrist.${extensionFor(wristFile.mimetype)}`, wristFile.buffer);
        await writeEpisodeFile("metadata.json", "metadata.json", JSON.stringify(metadata, null, 2));

        res.status(201).json({ episodeDir: episodeDirRelative });
      } catch (err: any) {
        console.error("Episode save error:", err);
        res.status(500).json({ error: err.message || "Failed to save episode to disk." });
      }
    }
  );

  // AI Sequence Trajectory Generation Endpoint
  app.post("/api/ollama/generate-sequence", async (req, res) => {
    try {
      const { prompt } = req.body;
      if (!prompt || typeof prompt !== 'string') {
        return res.status(400).json({ error: "Prompt string is required" });
      }
      const userPrompt = prompt.trim();
      const abortController = new AbortController();
      const timeout = setTimeout(() => abortController.abort(), 30_000);

      try {
        const response = await fetch(`${ollamaBaseUrl}/api/chat`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          signal: abortController.signal,
          body: JSON.stringify({
            model,
            stream: false,
            options: {
              temperature: 0.2,
              num_predict: 600
            },
          format: {
            type: "object",
            additionalProperties: false,
            properties: {
              title: { type: "string", description: "Action title" },
              description: { type: "string", description: "Detailed description of routine" },
              keyframes: {
                type: "array",
                items: {
                  type: "object",
                  additionalProperties: false,
                  properties: {
                    name: { type: "string" },
                    durationMs: { type: "number" },
                    delayAfterMs: { type: "number" },
                    joints: {
                      type: "object",
                      additionalProperties: false,
                      properties: {
                        base: { type: "number" },
                        shoulder: { type: "number" },
                        elbow: { type: "number" },
                        wristPitch: { type: "number" },
                        wristRoll: { type: "number" },
                        gripper: { type: "number" }
                      },
                      required: ["base", "shoulder", "elbow", "wristPitch", "wristRoll", "gripper"]
                    },
                    comment: { type: ["string", "null"] }
                  },
                  required: ["name", "durationMs", "delayAfterMs", "joints", "comment"]
                }
              }
            },
            required: ["title", "description", "keyframes"]
          },
            messages: [
            {
              role: "system",
              content: `You are an expert robotics kinematics engineer for the open-source SO-ARM100 (Standardized Open Arm 100) 6-DOF servo arm.

SO-ARM100 Servo limits & defaults:
- base: -180 to +180 deg (0 = center forward)
- shoulder: -90 to +90 deg (0 = upright, + = tilt forward)
- elbow: -120 to +120 deg (0 = straight, + = flex forward)
- wristPitch: -90 to +90 deg (0 = level, + = pitch up, - = pitch down)
- wristRoll: -180 to +180 deg (0 = neutral roll)
- gripper: 0 to 100 % (0 = closed claw, 100 = full open)

Ensure realistic smooth motion timing (durationMs between 600ms and 2000ms).
Create 3 to 5 logical step keyframes. Always end in a safe rest posture or completed goal pose.
Return only data matching the supplied JSON schema.`
            },
            {
              role: "user",
              content: `<user_request>\n${userPrompt}\n</user_request>\nCreate the movement sequence for this request.`
            }
            ]
          })
        });

        if (!response.ok) {
          const errorBody = await response.text();
          throw new Error(`Ollama request failed (${response.status}): ${errorBody}`);
        }

        const responseData = await response.json() as { message?: { content?: string } };
        const responseText = responseData.message?.content || "{}";
        const cleanedResponse = responseText
          .trim()
          .replace(/^```(?:json)?\s*/i, "")
          .replace(/\s*```$/, "");

        let sequenceData: unknown;
        try {
          sequenceData = JSON.parse(cleanedResponse);
        } catch {
          sequenceData = JSON.parse(jsonrepair(cleanedResponse));
        }
        try {
          res.json(sanitizeSequenceData(sequenceData));
        } catch (error) {
          console.warn("Ollama returned an unsupported sequence shape:", cleanedResponse.slice(0, 500));
          throw error;
        }
      } finally {
        clearTimeout(timeout);
      }
    } catch (err: any) {
      console.error("Ollama Trajectory Generation Error:", err);
      const message = err.name === "AbortError"
        ? "Ollama did not respond within 30 seconds. Try a shorter prompt or a faster model."
        : err.message || "Failed to generate sequence with AI";
      res.status(500).json({ error: message });
    }
  });

  // Mount Vite middleware for dev or static files for prod
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`[SO-ARM100] Server running on port ${PORT}`);
  });
}

startServer();
