import React, { useState } from 'react';
import { Sequence, Keyframe, JointState } from '../types';
import { PRESET_SEQUENCES } from '../constants';
import { interpolateJoints } from '../utils/kinematics';
import {
  Play, Pause, Square, Repeat, Plus, Trash2, ArrowUp, ArrowDown,
  Sparkles, Download, Upload, Copy, Check, Clock, Film, Layers, ShieldAlert, Code
} from 'lucide-react';

interface SequenceStudioProps {
  currentSequence: Sequence;
  onUpdateSequence: (seq: Sequence) => void;
  currentJoints: JointState;
  onPosePreview: (joints: JointState) => void;
  isPlaying: boolean;
  activeKeyframeIndex: number;
  onStartPlayback: () => void;
  onPausePlayback: () => void;
  onStopPlayback: () => void;
  onOpenAiGenerator: () => void;
}

export const SequenceStudio: React.FC<SequenceStudioProps> = ({
  currentSequence,
  onUpdateSequence,
  currentJoints,
  onPosePreview,
  isPlaying,
  activeKeyframeIndex,
  onStartPlayback,
  onPausePlayback,
  onStopPlayback,
  onOpenAiGenerator
}) => {
  const [copiedCode, setCopiedCode] = useState(false);
  const [showCodeModal, setShowCodeModal] = useState(false);

  // Add current joint pose as a new keyframe
  const handleCapturePose = () => {
    const newKf: Keyframe = {
      id: `kf-${Date.now()}`,
      name: `Pose ${currentSequence.keyframes.length + 1}`,
      durationMs: 1200,
      delayAfterMs: 300,
      joints: { ...currentJoints },
      comment: 'Captured pose snapshot'
    };

    onUpdateSequence({
      ...currentSequence,
      keyframes: [...currentSequence.keyframes, newKf]
    });
  };

  const handleUpdateKeyframe = (index: number, updated: Partial<Keyframe>) => {
    const nextKfs = [...currentSequence.keyframes];
    nextKfs[index] = { ...nextKfs[index], ...updated };
    onUpdateSequence({ ...currentSequence, keyframes: nextKfs });
  };

  const handleMoveKeyframe = (index: number, direction: 'up' | 'down') => {
    const targetIdx = direction === 'up' ? index - 1 : index + 1;
    if (targetIdx < 0 || targetIdx >= currentSequence.keyframes.length) return;

    const nextKfs = [...currentSequence.keyframes];
    const temp = nextKfs[index];
    nextKfs[index] = nextKfs[targetIdx];
    nextKfs[targetIdx] = temp;

    onUpdateSequence({ ...currentSequence, keyframes: nextKfs });
  };

  const handleDeleteKeyframe = (index: number) => {
    const nextKfs = currentSequence.keyframes.filter((_, i) => i !== index);
    onUpdateSequence({ ...currentSequence, keyframes: nextKfs });
  };

  const handleLoadPreset = (presetId: string) => {
    const found = PRESET_SEQUENCES.find(s => s.id === presetId);
    if (found) {
      onUpdateSequence({ ...found, id: `seq-${Date.now()}` });
    }
  };

  // Generate Python Script for SO-ARM100 Feetech / LeRobot execution
  const generatePythonScript = () => {
    const jsonStr = JSON.stringify(currentSequence.keyframes, null, 2);
    return `# SO-ARM100 Robot Sequence Execution Script
# Generated by SO-ARM100 Web Controller
import time
import json
from feetech_servo_sdk import PortHandler, PacketHandler

# Serial Port Configuration
PORT_NAME = "/dev/ttyUSB0" # or "COM3"
BAUDRATE = 1000000

print(f"Connecting to SO-ARM100 on {PORT_NAME} at {BAUDRATE} baud...")

# Trajectory Keyframes Data
KEYFRAMES = ${jsonStr}

def execute_sequence():
    print(f"Executing Routine: {currentSequence.title}")
    for idx, kf in enumerate(KEYFRAMES):
        print(f"[{idx + 1}/{len(KEYFRAMES)}] Moving to: {kf['name']}")
        joints = kf['joints']
        # Servo ticks calculation (0..4095)
        b = int((joints['base'] + 180) / 360 * 4095)
        s = int((joints['shoulder'] + 90) / 180 * 4095)
        e = int((joints['elbow'] + 120) / 240 * 4095)
        wp = int((joints['wristPitch'] + 90) / 180 * 4095)
        wr = int((joints['wristRoll'] + 180) / 360 * 4095)
        g = int(joints['gripper'] / 100 * 4095)
        
        # Send serial command packet
        print(f"Servos -> Base:{b}, Shoulder:{s}, Elbow:{e}, WristP:{wp}, WristR:{wr}, Gripper:{g}")
        time.sleep(kf['durationMs'] / 1000.0)
        time.sleep(kf['delayAfterMs'] / 1000.0)

if __name__ == "__main__":
    execute_sequence()
`;
  };

  const handleCopyCode = () => {
    navigator.clipboard.writeText(generatePythonScript());
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2000);
  };

  const handleExportJson = () => {
    const blob = new Blob([JSON.stringify(currentSequence, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${currentSequence.title.toLowerCase().replace(/\s+/g, '_')}_sequence.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleImportJson = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const parsed = JSON.parse(event.target?.result as string);
        if (parsed.keyframes && Array.isArray(parsed.keyframes)) {
          onUpdateSequence({
            ...parsed,
            id: `seq-${Date.now()}`
          });
        }
      } catch (err) {
        alert('Invalid JSON sequence file format');
      }
    };
    reader.readAsText(file);
  };

  return (
    <div className="bg-zinc-900 border border-zinc-800 rounded-sm p-6 shadow-2xl flex flex-col gap-6">
      {/* Studio Header & Main Actions */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-zinc-800">
        <div>
          <span className="text-[10px] uppercase tracking-[0.3em] text-zinc-500 font-bold block mb-0.5">
            Trajectory Engine
          </span>
          <h2 className="text-2xl font-black uppercase italic text-white tracking-tight">Keyframe Sequence Studio</h2>
        </div>

        {/* Action Toolbar */}
        <div className="flex items-center gap-2 flex-wrap">
          {/* Preset Selector */}
          <select
            onChange={e => handleLoadPreset(e.target.value)}
            defaultValue=""
            className="bg-zinc-950 text-zinc-200 text-xs px-3 py-2 rounded-sm border border-zinc-700 font-bold uppercase tracking-tight cursor-pointer"
          >
            <option value="" disabled>Load Preset Routine...</option>
            {PRESET_SEQUENCES.map(p => (
              <option key={p.id} value={p.id}>{p.title}</option>
            ))}
          </select>

          {/* AI Trajectory Launcher */}
          <button
            onClick={onOpenAiGenerator}
            className="px-4 py-2 bg-amber-400 hover:bg-amber-300 text-zinc-950 text-xs font-black uppercase tracking-tight rounded-sm shadow-[0_0_15px_rgba(251,191,36,0.3)] transition flex items-center gap-2"
          >
            <Sparkles className="w-4 h-4 fill-current" />
            <span>AI Trajectory (Gemini)</span>
          </button>
        </div>
      </div>

      {/* Routine Metadata & Global Settings Bar */}
      <div className="bg-zinc-950 p-4 rounded-sm border border-zinc-800 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="flex-1 w-full sm:w-auto">
          <input
            type="text"
            value={currentSequence.title}
            onChange={e => onUpdateSequence({ ...currentSequence, title: e.target.value })}
            className="bg-transparent text-white font-black text-base focus:outline-none border-b border-transparent focus:border-amber-400 w-full uppercase tracking-tight"
            placeholder="Sequence Title..."
          />
          <input
            type="text"
            value={currentSequence.description}
            onChange={e => onUpdateSequence({ ...currentSequence, description: e.target.value })}
            className="bg-transparent text-zinc-400 text-xs focus:outline-none border-b border-transparent focus:border-zinc-700 w-full mt-1"
            placeholder="Description..."
          />
        </div>

        {/* Playback Controls & Multipliers */}
        <div className="flex items-center gap-2 bg-zinc-900 p-1.5 rounded-sm border border-zinc-800">
          {!isPlaying ? (
            <button
              onClick={onStartPlayback}
              disabled={currentSequence.keyframes.length === 0}
              className="px-4 py-2 bg-emerald-500 hover:bg-emerald-400 disabled:opacity-50 text-zinc-950 text-xs font-black uppercase tracking-tight rounded-sm transition flex items-center gap-1.5 shadow"
            >
              <Play className="w-4 h-4 fill-current" />
              <span>PLAY</span>
            </button>
          ) : (
            <button
              onClick={onPausePlayback}
              className="px-4 py-2 bg-amber-400 hover:bg-amber-300 text-zinc-950 text-xs font-black uppercase tracking-tight rounded-sm transition flex items-center gap-1.5 shadow"
            >
              <Pause className="w-4 h-4 fill-current" />
              <span>PAUSE</span>
            </button>
          )}

          <button
            onClick={onStopPlayback}
            className="p-2 bg-zinc-800 hover:bg-zinc-700 text-zinc-300 rounded-sm transition"
            title="Stop & Reset to Start"
          >
            <Square className="w-4 h-4" />
          </button>

          <button
            onClick={() => onUpdateSequence({ ...currentSequence, loop: !currentSequence.loop })}
            className={`p-2 rounded-sm transition ${
              currentSequence.loop ? 'bg-amber-400 text-zinc-950' : 'bg-zinc-800 text-zinc-400 hover:text-zinc-200'
            }`}
            title="Toggle Continuous Loop"
          >
            <Repeat className="w-4 h-4" />
          </button>

          {/* Speed Multiplier */}
          <select
            value={currentSequence.speedMultiplier}
            onChange={e => onUpdateSequence({ ...currentSequence, speedMultiplier: parseFloat(e.target.value) })}
            className="bg-zinc-800 text-zinc-200 text-xs px-2 py-1.5 rounded-sm border border-zinc-700 font-mono font-bold"
          >
            <option value="0.25">0.25x</option>
            <option value="0.5">0.5x</option>
            <option value="1.0">1.0x</option>
            <option value="1.5">1.5x</option>
            <option value="2.0">2.0x</option>
          </select>
        </div>
      </div>

      {/* Keyframe Timeline Strip */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="text-xs font-black text-zinc-300 uppercase tracking-widest font-mono">
            Timeline Keyframes ({currentSequence.keyframes.length})
          </span>
          {activeKeyframeIndex >= 0 && isPlaying && (
            <span className="text-[10px] bg-amber-500/10 text-amber-400 px-2 py-0.5 rounded-sm border border-amber-500/30 animate-pulse font-mono font-bold uppercase">
              EXECUTING KF #{activeKeyframeIndex + 1}
            </span>
          )}
        </div>

        <button
          onClick={handleCapturePose}
          className="px-4 py-2 bg-amber-400 hover:bg-amber-300 text-zinc-950 text-xs font-black uppercase tracking-tight rounded-sm transition flex items-center gap-1.5 shadow-[0_0_15px_rgba(251,191,36,0.2)]"
        >
          <Plus className="w-4 h-4" />
          <span>Capture Current Pose</span>
        </button>
      </div>

      {/* Keyframe Cards Grid */}
      {currentSequence.keyframes.length === 0 ? (
        <div className="bg-zinc-950 border border-dashed border-zinc-800 rounded-sm p-8 text-center flex flex-col items-center gap-3">
          <Layers className="w-8 h-8 text-zinc-600" />
          <p className="text-xs text-zinc-400 max-w-sm">
            No keyframes captured yet. Move the 3D twin or physical arm joints and click <strong className="text-amber-400">Capture Current Pose</strong> to start building your routine.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3 max-h-[420px] overflow-y-auto pr-1">
          {currentSequence.keyframes.map((kf, index) => {
            const isActive = index === activeKeyframeIndex;

            return (
              <div
                key={kf.id}
                className={`p-4 rounded-sm border transition flex flex-col justify-between gap-3 ${
                  isActive
                    ? 'bg-zinc-900 border-l-4 border-l-amber-400 border-zinc-700 shadow-xl'
                    : 'bg-zinc-950 border-zinc-800 hover:border-zinc-700'
                }`}
              >
                {/* Keyframe Header */}
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="w-6 h-6 rounded-sm bg-zinc-800 text-amber-400 text-xs font-mono font-black flex items-center justify-center border border-zinc-700">
                      {index + 1}
                    </span>
                    <input
                      type="text"
                      value={kf.name}
                      onChange={e => handleUpdateKeyframe(index, { name: e.target.value })}
                      className="bg-transparent font-bold text-xs text-zinc-100 focus:outline-none border-b border-transparent focus:border-amber-400 uppercase tracking-tight"
                    />
                  </div>

                  {/* Move & Delete Tools */}
                  <div className="flex items-center gap-1">
                    <button
                      onClick={() => handleMoveKeyframe(index, 'up')}
                      disabled={index === 0}
                      className="p-1 text-zinc-400 hover:text-zinc-200 disabled:opacity-30"
                    >
                      <ArrowUp className="w-3.5 h-3.5" />
                    </button>
                    <button
                      onClick={() => handleMoveKeyframe(index, 'down')}
                      disabled={index === currentSequence.keyframes.length - 1}
                      className="p-1 text-zinc-400 hover:text-zinc-200 disabled:opacity-30"
                    >
                      <ArrowDown className="w-3.5 h-3.5" />
                    </button>
                    <button
                      onClick={() => handleDeleteKeyframe(index)}
                      className="p-1 text-rose-400 hover:text-rose-300"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>
                </div>

                {/* Joint Angle Snapshot Summary */}
                <div className="grid grid-cols-3 gap-1 bg-zinc-900 p-2.5 rounded-sm border border-zinc-800 font-mono text-[10px] text-zinc-400 font-bold">
                  <div>Base: <span className="text-amber-400">{kf.joints.base}°</span></div>
                  <div>Shldr: <span className="text-amber-400">{kf.joints.shoulder}°</span></div>
                  <div>Elbow: <span className="text-amber-400">{kf.joints.elbow}°</span></div>
                  <div>WristP: <span className="text-cyan-400">{kf.joints.wristPitch}°</span></div>
                  <div>WristR: <span className="text-cyan-400">{kf.joints.wristRoll}°</span></div>
                  <div>Claw: <span className="text-emerald-400">{kf.joints.gripper}%</span></div>
                </div>

                {/* Duration & Pause Timing Input */}
                <div className="grid grid-cols-2 gap-2 text-xs">
                  <div>
                    <label className="text-[10px] text-zinc-400 block mb-1 font-bold uppercase tracking-tight">Move Time (ms):</label>
                    <input
                      type="number"
                      value={kf.durationMs}
                      onChange={e => handleUpdateKeyframe(index, { durationMs: parseInt(e.target.value) || 500 })}
                      className="w-full bg-zinc-900 border border-zinc-800 rounded-sm px-2 py-1 text-zinc-200 font-mono text-xs font-bold"
                    />
                  </div>
                  <div>
                    <label className="text-[10px] text-zinc-400 block mb-1 font-bold uppercase tracking-tight">Pause Delay (ms):</label>
                    <input
                      type="number"
                      value={kf.delayAfterMs}
                      onChange={e => handleUpdateKeyframe(index, { delayAfterMs: parseInt(e.target.value) || 0 })}
                      className="w-full bg-zinc-900 border border-zinc-800 rounded-sm px-2 py-1 text-zinc-200 font-mono text-xs font-bold"
                    />
                  </div>
                </div>

                {/* Preview Pose Button */}
                <button
                  onClick={() => onPosePreview(kf.joints)}
                  className="w-full py-1.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-200 text-xs font-black uppercase tracking-tight rounded-sm border border-zinc-700 transition flex items-center justify-center gap-1"
                >
                  <span>Preview Pose in 3D</span>
                </button>
              </div>
            );
          })}
        </div>
      )}

      {/* Footer Export & Code Tools */}
      <div className="flex items-center justify-between pt-3 border-t border-zinc-800 text-xs">
        <div className="flex items-center gap-2">
          <button
            onClick={() => setShowCodeModal(true)}
            className="px-3.5 py-1.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-100 rounded-sm border border-zinc-700 transition flex items-center gap-1.5 font-black uppercase tracking-tight"
          >
            <Code className="w-3.5 h-3.5 text-amber-400" />
            <span>Export LeRobot Python Code</span>
          </button>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleExportJson}
            className="px-3.5 py-1.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-100 rounded-sm border border-zinc-700 transition flex items-center gap-1.5 font-black uppercase tracking-tight"
          >
            <Download className="w-3.5 h-3.5 text-emerald-400" />
            <span>Save JSON</span>
          </button>

          <label className="px-3.5 py-1.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-100 rounded-sm border border-zinc-700 transition flex items-center gap-1.5 cursor-pointer font-black uppercase tracking-tight">
            <Upload className="w-3.5 h-3.5 text-cyan-400" />
            <span>Load JSON</span>
            <input type="file" accept=".json" onChange={handleImportJson} className="hidden" />
          </label>
        </div>
      </div>

      {/* LeRobot Python Code Export Modal */}
      {showCodeModal && (
        <div className="fixed inset-0 z-50 bg-black/85 backdrop-blur-md flex items-center justify-center p-4">
          <div className="bg-zinc-950 border border-zinc-800 rounded-sm w-full max-w-2xl overflow-hidden shadow-2xl flex flex-col max-h-[85vh]">
            <div className="p-4 border-b border-zinc-800 flex items-center justify-between bg-zinc-900">
              <div className="flex items-center gap-2">
                <Code className="w-5 h-5 text-amber-400" />
                <h3 className="text-sm font-black uppercase italic text-zinc-100">Python LeRobot Driver Export</h3>
              </div>
              <button
                onClick={() => setShowCodeModal(false)}
                className="text-zinc-400 hover:text-white text-xs px-2.5 py-1 rounded-sm bg-zinc-800 font-bold uppercase border border-zinc-700"
              >
                Close
              </button>
            </div>

            <div className="p-4 overflow-y-auto font-mono text-xs bg-zinc-950 text-zinc-300 leading-relaxed">
              <pre>{generatePythonScript()}</pre>
            </div>

            <div className="p-4 border-t border-zinc-800 flex items-center justify-between bg-zinc-900">
              <span className="text-xs text-zinc-400 font-mono">
                Executable with Python 3.10+ & Feetech STS3215 servo driver.
              </span>
              <button
                onClick={handleCopyCode}
                className="px-4 py-2 bg-amber-400 hover:bg-amber-300 text-zinc-950 font-black text-xs uppercase tracking-tight rounded-sm flex items-center gap-1.5 shadow"
              >
                {copiedCode ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                <span>{copiedCode ? 'COPIED SCRIPT!' : 'COPY SCRIPT'}</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
